"""Modal sandbox generation for hosted Invoke agents."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import textwrap
import time
from pathlib import Path
from typing import Any

from .deploy import DeployPlan


ENDPOINT_RE = re.compile(r"https://[^\s\"']+modal\.run[^\s\"']*")


def _require_modal_cli() -> None:
    if shutil.which("modal"):
        return
    raise RuntimeError(
        "Modal CLI is required for `invoke deploy` agent deployments. "
        "Install and authenticate it with `pip install modal` and `modal setup`, "
        "or run `invoke deploy --dry-run` to inspect the generated deployment first."
    )


def _remote_entrypoint_command(entrypoint: str) -> str:
    quoted = json.dumps(entrypoint)
    return textwrap.dedent(
        f"""\
        def agent_command(prompt):
            entrypoint = {quoted}
            source = Path("/workspace") / entrypoint
            if entrypoint.endswith(".py"):
                return ["python", "/workspace/.invoke_runtime/instrumented_agent.py", str(source), prompt]
            if entrypoint.endswith(".ts"):
                compiled = Path("/workspace/dist") / Path(entrypoint).with_suffix(".js").name
                if compiled.exists():
                    return ["node", str(compiled), prompt]
                return ["npx", "tsx", str(source), prompt]
            return ["node", str(source), prompt]
        """
    )


def modal_source(plan: DeployPlan) -> str:
    """Build the deployable Modal source file for one agent project."""

    app_name = json.dumps(plan.app_name)
    volume_name = json.dumps(plan.modal_volume)
    project_root = json.dumps(plan.project_root)
    invoke_package_root = json.dumps(str(Path(__file__).parent.resolve()))
    runtime_root = json.dumps(str(Path(plan.project_root) / ".invoke_runtime"))
    env_keys = json.dumps(sorted(plan.env), sort_keys=True)
    robustness = repr(dict(sorted(plan.robustness.items())))
    endpoint_name = json.dumps(plan.endpoint_name)
    agent_command_source = _remote_entrypoint_command(plan.entrypoint).rstrip()

    template = textwrap.dedent(
        f"""\
        # Generated by Invoke. Do not edit by hand; rerun `invoke deploy`.
        from __future__ import annotations

        import json
        import os
        import sqlite3
        import subprocess
        import time
        import uuid
        from dataclasses import asdict, dataclass, field
        from datetime import datetime
        from pathlib import Path
        from typing import Any

        import modal
        from fastapi import Request


        APP_NAME = {app_name}
        VOLUME_NAME = {volume_name}
        PROJECT_ROOT = {project_root}
        INVOKE_PACKAGE_ROOT = {invoke_package_root}
        INVOKE_RUNTIME_ROOT = {runtime_root}
        INVOKE_ENV_KEYS = {env_keys}
        INVOKE_ENV = {{key: os.environ[key] for key in INVOKE_ENV_KEYS if os.environ.get(key)}}
        INVOKE_ROBUSTNESS = {robustness}

        app = modal.App(APP_NAME)
        volume = modal.Volume.from_name(VOLUME_NAME, create_if_missing=True)

        image = (
            modal.Image.debian_slim(python_version="3.11")
            .apt_install("nodejs", "npm")
            .pip_install("fastapi[standard]")
            .add_local_dir(
                PROJECT_ROOT,
                remote_path="/workspace",
                copy=True,
                ignore=[
                    ".git",
                    ".invoke",
                    ".invoke_runtime",
                    "node_modules",
                    "dist",
                    ".next",
                    "__pycache__",
                    "*.tgz",
                ],
            )
            .add_local_dir(
                INVOKE_PACKAGE_ROOT,
                remote_path="/workspace/invoke",
                copy=True,
                ignore=[
                    "__pycache__",
                    "*.pyc",
                    "templates/claude-agent-sdk/node_modules",
                    "templates/claude-agent-sdk/dist",
                ],
            )
            .add_local_dir(
                INVOKE_RUNTIME_ROOT,
                remote_path="/workspace/.invoke_runtime",
                copy=True,
                ignore=["__pycache__", "*.pyc"],
            )
            .run_commands(
                "cd /workspace && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
                "cd /workspace && if [ -f pyproject.toml ] && grep -q '^\\\\[project\\\\]' pyproject.toml; then pip install -e .; fi",
                "cd /workspace && if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm install; fi",
                "cd /workspace && if [ -f package.json ]; then npm run build --if-present; fi",
            )
        )

        function_secrets = [modal.Secret.from_dict(INVOKE_ENV)] if INVOKE_ENV else []


        def utc_ms():
            return int(time.time() * 1000)


        def append_jsonl(path, payload):
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(payload, sort_keys=True) + "\\n")


        def read_jsonl(path):
            if not path.exists():
                return []
            rows = []
            for line in path.read_text(encoding="utf-8").splitlines():
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
            return rows


        @dataclass
        class AgentTrace:
            trace_id: str
            agent_id: str
            agent_name: str
            timestamp: datetime
            status: str
            execution_id: str | None = None
            action: str | None = None
            stage: str | None = None
            data: dict[str, Any] = field(default_factory=dict)

            def model_dump(self):
                payload = asdict(self)
                payload["timestamp"] = self.timestamp.isoformat()
                return payload

            def model_dump_json(self):
                return json.dumps(self.model_dump(), sort_keys=True)


        def trace_db_path():
            return Path("/state/traces.db")


        def ensure_trace_db():
            path = trace_db_path()
            path.parent.mkdir(parents=True, exist_ok=True)
            conn = sqlite3.connect(path)
            conn.execute(
                '''
                CREATE TABLE IF NOT EXISTS traces (
                    trace_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    agent_name TEXT NOT NULL,
                    timestamp TEXT NOT NULL,
                    status TEXT NOT NULL,
                    execution_id TEXT,
                    action TEXT,
                    stage TEXT,
                    data TEXT NOT NULL
                )
                '''
            )
            return conn


        async def store_trace(trace: AgentTrace):
            payload = trace.model_dump()
            conn = ensure_trace_db()
            try:
                conn.execute(
                    '''
                    INSERT OR REPLACE INTO traces
                    (trace_id, agent_id, agent_name, timestamp, status, execution_id, action, stage, data)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ''',
                    (
                        trace.trace_id,
                        trace.agent_id,
                        trace.agent_name,
                        payload["timestamp"],
                        trace.status,
                        trace.execution_id,
                        trace.action,
                        trace.stage,
                        trace.model_dump_json(),
                    ),
                )
                conn.commit()
            finally:
                conn.close()
            append_jsonl(Path("/state/agent_traces.jsonl"), payload)


        async def record_trace(data: dict):
            trace = AgentTrace(
                trace_id=data.get("trace_id") or data.get("execution_id") or "trace_" + uuid.uuid4().hex[:12],
                agent_id=data.get("agent_id") or APP_NAME,
                agent_name=data.get("agent_name") or APP_NAME,
                timestamp=datetime.utcnow(),
                status=data.get("status") or "event",
                execution_id=data.get("execution_id"),
                action=data.get("action"),
                stage=data.get("stage"),
                data=data,
            )
            await store_trace(trace)


        def onyx_summarize(traces):
            recent = traces[-50:]
            groups = {{}}
            for trace in recent:
                action = str(trace.get("action") or "").lower()
                outcome = str(trace.get("final_outcome") or trace.get("status") or "").lower()
                events = trace.get("events") if isinstance(trace.get("events"), list) else []
                event_text = " ".join(str(event.get("step") or "") + " " + str(event.get("status") or "") for event in events if isinstance(event, dict)).lower()
                key = None
                if "timeout" in outcome or "timeout" in event_text:
                    key = "timeout_unknown_effect"
                elif "blocked_by_policy" in outcome or action == "database.execute":
                    key = "policy_block"
                elif "duplicate" in outcome or "idempotent" in event_text:
                    key = "duplicate_retry"
                elif "state_reconciled changed" in event_text or "state_revalidated changed" in event_text:
                    key = "state_drift"
                if key:
                    groups[key] = groups.get(key, 0) + 1

            suggestions = []
            if groups.get("timeout_unknown_effect", 0) >= 2:
                suggestions.append({{
                    "title": "Require reconciliation before retry",
                    "severity": "high",
                    "confidence": 90,
                    "reason": f"Seen {{groups['timeout_unknown_effect']}} unknown-effect timeout traces.",
                    "one_click_patch": {{"retry_strategy": "reconcile_before_retry"}},
                }})
            if groups.get("duplicate_retry", 0) >= 2:
                suggestions.append({{
                    "title": "Require idempotency keys",
                    "severity": "high",
                    "confidence": 88,
                    "reason": f"Seen {{groups['duplicate_retry']}} duplicate retry traces.",
                    "one_click_patch": {{"idempotency": {{"mode": "required"}}}},
                }})
            if groups.get("policy_block", 0) >= 1:
                suggestions.append({{
                    "title": "Keep unsafe actions in preflight",
                    "severity": "high",
                    "confidence": 86,
                    "reason": f"Seen {{groups['policy_block']}} policy-blocked unsafe actions.",
                    "one_click_patch": {{"preflight": {{"block": ["database.execute", "*.delete"]}}}},
                }})
            if groups.get("state_drift", 0) >= 1:
                suggestions.append({{
                    "title": "Revalidate state before resume",
                    "severity": "high",
                    "confidence": 87,
                    "reason": f"Seen {{groups['state_drift']}} state drift traces.",
                    "one_click_patch": {{"freeze_thaw": {{"revalidate_before_resume": True}}}},
                }})
            return {{
                "enabled": True,
                "mode": "deterministic",
                "status": "watching",
                "trace_count": len(recent),
                "suggestions": suggestions[:3],
            }}


        def evaluate_policy(action, params):
            lowered = str(action).lower()
            sql = str(params.get("sql", "")).lower() if isinstance(params, dict) else ""
            if action == "database.execute" or "disable row level security" in sql or "drop table" in sql:
                return {{
                    "effect": "block",
                    "risk": "high",
                    "reason": "Direct database execution can bypass application policy or row-level security.",
                    "guardrails": ["policy_block", "sandbox_required"],
                }}
            if any(word in lowered for word in ("delete", "refund", "charge", "transfer")):
                return {{
                    "effect": "require_approval",
                    "risk": "high",
                    "reason": "Financial or destructive action requires approval and reconciliation.",
                    "guardrails": ["approval", "idempotency_key", "state_reconciliation"],
                }}
            return {{
                "effect": "allow",
                "risk": "low",
                "reason": "No blocking policy matched.",
                "guardrails": ["trace"],
            }}


        def reconcile_state(expected, live):
            drift = []
            if isinstance(expected, dict) and isinstance(live, dict):
                for key, expected_value in expected.items():
                    if live.get(key) != expected_value:
                        drift.append({{"key": key, "expected": expected_value, "live": live.get(key)}})
            return {{"status": "changed" if drift else "valid", "drift": drift, "checked_at_ms": utc_ms()}}


        def extract_action(payload):
            raw = payload.get("action") or {{}}
            if isinstance(raw, str):
                return raw, payload.get("params") or {{}}
            if isinstance(raw, dict):
                return raw.get("action") or raw.get("name") or "agent.run", raw.get("params") or {{}}
            return "agent.run", {{}}


        def checkpoint_path():
            return Path("/state/checkpoints.jsonl")


        def trace_path():
            return Path("/state/traces.jsonl")


        def freeze_execution(execution_id, action, params, context):
            checkpoint = {{
                "checkpoint_id": "freeze_" + uuid.uuid4().hex[:12],
                "execution_id": execution_id,
                "action": action,
                "params": params,
                "context_snapshot": context,
                "created_at_ms": utc_ms(),
            }}
            append_jsonl(checkpoint_path(), checkpoint)
            return checkpoint


        def find_checkpoint(checkpoint_id):
            for checkpoint in reversed(read_jsonl(checkpoint_path())):
                if checkpoint.get("checkpoint_id") == checkpoint_id:
                    return checkpoint
            return None


        __AGENT_COMMAND_SOURCE__


        @app.function(image=image, volumes={{"/state": volume}}, secrets=function_secrets, timeout=60 * 20)
        @modal.fastapi_endpoint(method="POST", label={endpoint_name})
        async def invoke(request: Request):
            started = utc_ms()
            payload = await request.json()
            execution_id = payload.get("execution_id") or "exec_" + uuid.uuid4().hex[:12]
            prompt = payload.get("prompt") or payload.get("input") or ""
            agent_id = payload.get("agent_id") or APP_NAME
            action, params = extract_action(payload)
            events = []

            def event(step, status, detail=None):
                item = {{"step": step, "status": status, "timestamp_ms": utc_ms(), "detail": detail or {{}}}}
                events.append(item)
                return item

            event("request_received", "ok", {{"agent_id": agent_id, "action": action}})
            event("invoke_supervisor_loaded", "ok", INVOKE_ROBUSTNESS)
            await record_trace({{
                "trace_id": execution_id + ":request_received",
                "execution_id": execution_id,
                "agent_id": agent_id,
                "agent_name": APP_NAME,
                "action": action,
                "stage": "request_received",
                "status": "received",
                "prompt_present": bool(prompt),
            }})

            if not isinstance(params, dict):
                event("schema_checked", "failed", {{"reason": "params must be an object"}})
                trace = {{
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "action": action,
                    "status": "blocked",
                    "risk": "medium",
                    "final_outcome": "blocked_by_schema",
                    "events": events,
                    "latency_ms": utc_ms() - started,
                }}
                append_jsonl(trace_path(), trace)
                await record_trace({{
                    "trace_id": execution_id + ":schema_blocked",
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "agent_name": APP_NAME,
                    "action": action,
                    "stage": "schema_checked",
                    "status": "blocked",
                    "reason": "params must be an object",
                    "trace": trace,
                }})
                return {{
                    "success": False,
                    "execution": trace,
                    "error": "params must be an object",
                    "onyx": onyx_summarize(read_jsonl(trace_path())),
                }}
            event("schema_checked", "ok")

            if payload.get("resume_checkpoint_id"):
                checkpoint = find_checkpoint(payload["resume_checkpoint_id"])
                if not checkpoint:
                    event("checkpoint_loaded", "missing", {{"checkpoint_id": payload["resume_checkpoint_id"]}})
                    await record_trace({{
                        "trace_id": execution_id + ":checkpoint_missing",
                        "execution_id": execution_id,
                        "agent_id": agent_id,
                        "agent_name": APP_NAME,
                        "action": action,
                        "stage": "checkpoint_loaded",
                        "status": "blocked",
                        "checkpoint_id": payload["resume_checkpoint_id"],
                    }})
                    return {{"success": False, "execution_id": execution_id, "error": "checkpoint not found", "events": events}}
                event("checkpoint_loaded", "ok", {{"checkpoint_id": checkpoint["checkpoint_id"]}})
                revalidation = reconcile_state(checkpoint.get("context_snapshot") or {{}}, payload.get("live_context") or {{}})
                event("state_revalidated", revalidation["status"], revalidation)
                if revalidation["status"] == "changed":
                    trace = {{
                        "execution_id": execution_id,
                        "agent_id": agent_id,
                        "action": action,
                        "status": "requeued",
                        "risk": "high",
                        "final_outcome": "requeued_due_to_state_drift",
                        "events": events,
                        "latency_ms": utc_ms() - started,
                    }}
                    append_jsonl(trace_path(), trace)
                    await record_trace({{
                        "trace_id": execution_id + ":state_requeued",
                        "execution_id": execution_id,
                        "agent_id": agent_id,
                        "agent_name": APP_NAME,
                        "action": action,
                        "stage": "state_revalidated",
                        "status": "requeued",
                        "revalidation": revalidation,
                        "trace": trace,
                    }})
                    return {{
                        "success": True,
                        "status": "requeued",
                        "execution": trace,
                        "onyx": onyx_summarize(read_jsonl(trace_path())),
                    }}

            policy = evaluate_policy(action, params)
            event("policy_evaluated", "ok", policy)
            if policy["effect"] == "block":
                trace = {{
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "action": action,
                    "status": "blocked",
                    "risk": policy["risk"],
                    "policy": policy,
                    "final_outcome": "blocked_by_policy",
                    "events": events,
                    "latency_ms": utc_ms() - started,
                }}
                append_jsonl(trace_path(), trace)
                await record_trace({{
                    "trace_id": execution_id + ":policy_blocked",
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "agent_name": APP_NAME,
                    "action": action,
                    "stage": "policy_evaluated",
                    "status": "blocked",
                    "risk": policy["risk"],
                    "policy": policy,
                    "trace": trace,
                }})
                return {{
                    "success": True,
                    "status": "blocked",
                    "execution": trace,
                    "certificate_returned": True,
                    "onyx": onyx_summarize(read_jsonl(trace_path())),
                }}

            if policy["effect"] == "require_approval" and not payload.get("approved"):
                checkpoint = freeze_execution(
                    execution_id,
                    action,
                    params,
                    payload.get("context_snapshot") or payload.get("expected_state") or {{}},
                )
                event("execution_frozen", "pending_approval", {{"checkpoint_id": checkpoint["checkpoint_id"]}})
                trace = {{
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "action": action,
                    "status": "pending_approval",
                    "risk": policy["risk"],
                    "policy": policy,
                    "checkpoint": checkpoint,
                    "final_outcome": "frozen_for_human_review",
                    "events": events,
                    "latency_ms": utc_ms() - started,
                }}
                append_jsonl(trace_path(), trace)
                await record_trace({{
                    "trace_id": execution_id + ":frozen",
                    "execution_id": execution_id,
                    "agent_id": agent_id,
                    "agent_name": APP_NAME,
                    "action": action,
                    "stage": "freeze_thaw_hitl",
                    "status": "pending_approval",
                    "risk": policy["risk"],
                    "checkpoint": checkpoint,
                    "trace": trace,
                }})
                return {{
                    "success": True,
                    "status": "pending_approval",
                    "execution": trace,
                    "certificate_returned": True,
                    "onyx": onyx_summarize(read_jsonl(trace_path())),
                }}

            if payload.get("expected_state") is not None or payload.get("live_state") is not None:
                reconciliation = reconcile_state(payload.get("expected_state") or {{}}, payload.get("live_state") or {{}})
                event("state_reconciled", reconciliation["status"], reconciliation)
                if reconciliation["status"] == "changed":
                    trace = {{
                        "execution_id": execution_id,
                        "agent_id": agent_id,
                        "action": action,
                        "status": "blocked",
                        "risk": "high",
                        "policy": policy,
                        "reconciliation": reconciliation,
                        "final_outcome": "blocked_due_to_state_drift",
                        "events": events,
                        "latency_ms": utc_ms() - started,
                    }}
                    append_jsonl(trace_path(), trace)
                    await record_trace({{
                        "trace_id": execution_id + ":state_blocked",
                        "execution_id": execution_id,
                        "agent_id": agent_id,
                        "agent_name": APP_NAME,
                        "action": action,
                        "stage": "state_reconciled",
                        "status": "blocked",
                        "risk": "high",
                        "reconciliation": reconciliation,
                        "trace": trace,
                    }})
                    return {{
                        "success": True,
                        "status": "blocked",
                        "execution": trace,
                        "certificate_returned": True,
                        "onyx": onyx_summarize(read_jsonl(trace_path())),
                    }}

            event("agent_execution_started", "ok")
            await record_trace({{
                "trace_id": execution_id + ":agent_started",
                "execution_id": execution_id,
                "agent_id": agent_id,
                "agent_name": APP_NAME,
                "action": action,
                "stage": "agent_execution_started",
                "status": "running",
                "risk": policy["risk"],
                "policy": policy,
            }})
            completed = subprocess.run(
                agent_command(str(prompt)),
                cwd="/workspace",
                text=True,
                capture_output=True,
                timeout=int(payload.get("timeout_seconds") or 60 * 15),
                check=False,
            )
            status = "succeeded" if completed.returncode == 0 else "failed"
            event("agent_execution_completed", status, {{"returncode": completed.returncode}})
            trace = {{
                "execution_id": execution_id,
                "agent_id": agent_id,
                "action": action,
                "status": status,
                "risk": policy["risk"],
                "policy": policy,
                "final_outcome": status,
                "events": events,
                "latency_ms": utc_ms() - started,
                "stdout": completed.stdout[-8000:],
                "stderr": completed.stderr[-8000:],
                "certificate_returned": True,
            }}
            append_jsonl(trace_path(), trace)
            await record_trace({{
                "trace_id": execution_id + ":final",
                "execution_id": execution_id,
                "agent_id": agent_id,
                "agent_name": APP_NAME,
                "action": action,
                "stage": "agent_execution_completed",
                "status": status,
                "risk": policy["risk"],
                "policy": policy,
                "final_outcome": status,
                "latency_ms": trace["latency_ms"],
                "trace": trace,
            }})
            return {{
                "success": completed.returncode == 0,
                "execution": trace,
                "certificate_returned": True,
                "onyx": onyx_summarize(read_jsonl(trace_path())),
            }}
        """
    )
    return template.replace("__AGENT_COMMAND_SOURCE__", agent_command_source)


def runtime_wrapper_source(plan: DeployPlan) -> str:
    agent_id = json.dumps(plan.app_name)
    agent_name = json.dumps(plan.app_name)
    return textwrap.dedent(
        f"""\
        # Generated by Invoke. Runs the user agent with in-process tracing.
        from __future__ import annotations

        import asyncio
        import importlib.util
        import inspect
        import json
        import runpy
        import sys
        from pathlib import Path
        from typing import Any

        from invoke.sdk.trace_wrapper import InvokeTracer, safe_json, set_tracer, with_invoke_tracing


        DEFAULT_AGENT_ID = {agent_id}
        DEFAULT_AGENT_NAME = {agent_name}


        def load_module(path: Path):
            spec = importlib.util.spec_from_file_location("invoke_user_agent", path)
            if spec is None or spec.loader is None:
                raise RuntimeError(f"Could not load agent entrypoint: {{path}}")
            module = importlib.util.module_from_spec(spec)
            sys.modules["invoke_user_agent"] = module
            spec.loader.exec_module(module)
            return module


        def find_run_function(module):
            for name in ("run_agent", "main", "run"):
                candidate = getattr(module, name, None)
                if callable(candidate):
                    return candidate
            return None


        async def call_run_function(func, payload: dict[str, Any]):
            wrapped = with_invoke_tracing(func)
            signature = inspect.signature(func)
            required = [
                param
                for param in signature.parameters.values()
                if param.default is inspect._empty
                and param.kind in (param.POSITIONAL_ONLY, param.POSITIONAL_OR_KEYWORD, param.KEYWORD_ONLY)
            ]
            if not required:
                return await wrapped()
            return await wrapped(payload)


        async def main():
            if len(sys.argv) < 2:
                raise SystemExit("Usage: instrumented_agent.py <entrypoint> [prompt]")
            target = Path(sys.argv[1])
            prompt = sys.argv[2] if len(sys.argv) > 2 else ""
            payload = {{"prompt": prompt}}

            set_tracer(
                InvokeTracer(
                    agent_id=DEFAULT_AGENT_ID,
                    agent_name=DEFAULT_AGENT_NAME,
                    state_dir="/state",
                )
            )

            module = load_module(target)
            func = find_run_function(module)
            if func is None:
                # Last-resort compatibility for script-style agents. The outer Modal
                # supervisor still records boundary traces for this path.
                runpy.run_path(str(target), run_name="__main__")
                return

            result = await call_run_function(func, payload)
            print(json.dumps(safe_json(result), sort_keys=True))


        if __name__ == "__main__":
            asyncio.run(main())
        """
    )


def write_runtime_wrapper(plan: DeployPlan) -> Path:
    runtime_dir = Path(plan.project_root) / ".invoke_runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    path = runtime_dir / "instrumented_agent.py"
    path.write_text(runtime_wrapper_source(plan), encoding="utf-8")
    return path


def write_modal_source(plan: DeployPlan) -> Path:
    state_dir = Path(plan.project_root) / ".invoke"
    state_dir.mkdir(parents=True, exist_ok=True)
    write_runtime_wrapper(plan)
    path = state_dir / "modal_app.py"
    path.write_text(modal_source(plan), encoding="utf-8")
    return path


def _parse_endpoint(output: str) -> str | None:
    match = ENDPOINT_RE.search(output)
    return match.group(0).rstrip(".,)")


def deploy_modal_app(plan: DeployPlan) -> dict[str, Any]:
    """Deploy the generated Modal app and return endpoint metadata."""

    _require_modal_cli()
    source_path = write_modal_source(plan)
    timeout_seconds = int(os.getenv("INVOKE_MODAL_DEPLOY_TIMEOUT_SECONDS", str(60 * 20)))
    command = ["modal", "deploy", str(source_path)]
    process = subprocess.Popen(
        command,
        cwd=plan.project_root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
    )
    output_lines: list[str] = []
    started_at = time.monotonic()

    assert process.stdout is not None
    while True:
        line = process.stdout.readline()
        if line:
            print(line, end="", flush=True)
            output_lines.append(line)
        if process.poll() is not None:
            remaining = process.stdout.read()
            if remaining:
                print(remaining, end="", flush=True)
                output_lines.append(remaining)
            break
        if time.monotonic() - started_at > timeout_seconds:
            process.kill()
            remaining = process.stdout.read()
            if remaining:
                print(remaining, end="", flush=True)
                output_lines.append(remaining)
            output = "".join(output_lines)
            manual = " ".join(command)
            raise RuntimeError(
                "Modal deploy timed out after "
                f"{timeout_seconds} seconds.\n\n"
                "The generated Modal app is still available, so you can retry directly:\n"
                f"  cd {plan.project_root}\n"
                f"  {manual}\n\n"
                "To give Invoke more time next run, set:\n"
                "  export INVOKE_MODAL_DEPLOY_TIMEOUT_SECONDS=1800\n\n"
                f"Partial Modal output:\n{output.strip()}"
            )
        time.sleep(0.1)

    output = "".join(output_lines)
    if process.returncode != 0:
        raise RuntimeError(f"Modal deploy failed with exit code {process.returncode}:\n{output.strip()}")

    endpoint_url = _parse_endpoint(output)
    return {
        "app_name": plan.app_name,
        "volume": plan.modal_volume,
        "endpoint_url": endpoint_url,
        "dashboard_url": f"https://modal.com/apps/{plan.app_name}",
        "source_path": str(source_path),
        "deploy_output": output.strip(),
    }
